directory: /nfs/Music/Beets
library: ~/.beetslibrary.db
art_filename: cover
ui:
    color: yes
import:
    move: no
    bell: yes
    log: ~/.beetslog
paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track - $title
#    albumtype:soundtrack: Soundtracks/$album/$track - $title
plugins: fetchart embedart
